"""Add new venue fields

Revision ID: 011c689fcc5f
Revises: a15cb08491df
Create Date: 2023-12-21 15:09:27.010218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011c689fcc5f'
down_revision = 'a15cb08491df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('address_2')
        batch_op.drop_column('address_1')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
