"""empty message

Revision ID: 3f7893c68822
Revises: a39f3da43369
Create Date: 2023-12-22 21:08:18.225370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7893c68822'
down_revision = 'a39f3da43369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter_created', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_events', schema=None) as batch_op:
        batch_op.drop_column('newsletter_created')

    # ### end Alembic commands ###
