"""Add description to venues

Revision ID: 819a44d43cf0
Revises: d143ac537fa4
Create Date: 2023-12-27 01:56:37.173474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819a44d43cf0'
down_revision = 'd143ac537fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
